In [0]:
import torch
import torch.nn as nn

In [70]:
torch.cuda.is_available()

True

In [0]:
# # let us run this cell only if CUDA is available
# # We will use ``torch.device`` objects to move tensors in and out of GPU
# if torch.cuda.is_available():
#     device = torch.device("cuda")          # a CUDA device object
#     y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
#     x = x.to(device)                       # or just use strings ``.to("cuda")``
#     z = x + y
#     print(z)
#     print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [72]:
! python --version

Python 3.6.9


### A (very small) introduction to pytorch

Pytorch Tensors are very similar to Numpy arrays, with the added benefit of being usable on GPU. For a short tutorial on various methods to create tensors of particular types, see [this link](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py).
The important things to note are that Tensors can be created empty, from lists, and it is very easy to convert a numpy array into a pytorch tensor, and inversely.
One very important way to manipulate tensors that is different from numpy is the method ```.view``` which is used, as ```reshape```, to change the shape of a tensor. The difference is that ```.view``` will avoid making a copy of the tensor. 

In [73]:
a = torch.LongTensor(5)
b = torch.LongTensor([5])

print(a)
print(b)

tensor([         1935100736,                  32,          4294967295,
        3630571113557484390, 3617628775105509173])
tensor([5])


In [74]:
a = torch.FloatTensor([2])
b = torch.FloatTensor([3])

print(a + b)

tensor([5.])


The main interest in us using Pytorch is the ```autograd``` package. ```torch.Tensor```objects have an attribute ```.requires_grad```; if set as True, it starts to track all operations on it. When you finish your computation, can call ```.backward()``` and all the gradients are computed automatically (and stored in the ```.grad``` attribute).

One way to easily cut a tensor from the computational once it is not needed anymore is to use ```.detach()```.
More info on automatic differentiation in pytorch on [this link](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py).

In [75]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [76]:
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
for name, p in linear.named_parameters():
    print(name)
    print(p)

# Build loss function - Mean Square Error
criterion = nn.MSELoss()

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('Initial loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

weight
Parameter containing:
tensor([[-0.2802,  0.3308,  0.1238],
        [-0.3682,  0.1061, -0.5716]], requires_grad=True)
bias
Parameter containing:
tensor([ 0.5730, -0.0342], requires_grad=True)
Initial loss:  1.9507572650909424
dL/dw:  tensor([[ 0.0426,  0.4599, -0.0240],
        [-1.3008, -0.4855, -0.9547]])
dL/db:  tensor([0.9605, 0.3847])


In [77]:
# You can perform gradient descent manually, with an in-place update ...
linear.weight.data.sub_(0.01 * linear.weight.grad.data)
linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Loss after one update: ', loss.item())

Loss after one update:  1.909816026687622


In [78]:
# Use the optim package to define an Optimizer that will update the weights of the model.
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# By default, gradients are accumulated in buffers( i.e, not overwritten) whenever .backward()
# is called. Before the backward pass, we need to use the optimizer object to zero all of the
# gradients.
optimizer.zero_grad()
loss.backward()

# Calling the step function on an Optimizer makes an update to its parameters
optimizer.step()

# Print out the loss after the second step of gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Loss after two updates: ', loss.item())

Loss after two updates:  1.8700462579727173


### Tools for data processing 

In [0]:
import os
import time
import math
from collections import Counter
import pprint
pp = pprint.PrettyPrinter(indent=1)

We create a ```Dictionary``` class, that we are going to use to create a vocabulary for our text data. The goal here is to have a convenient tool, with easy access to any information we could need:
- A python dictionary ```word2idx``` allowing easy transformation of tokenized text into indexes
- A list ```idx2word```, allowing us to find the word corresponding to an index (for interpretation and generation)
- A python dictionary ```counter``` used to build the vocabulary, that can provide us with frequency information if needed. 
- The ```total``` count of words in the dictionary.

Important: The data that we are going to use are already pre-processed so we don't need to create special tokens and control the size of the vocabulary ourselves. However, when the text data is raw, methods to preprocess it conveniently should be added here. 

In [0]:
class Dictionary(object):
    def __init__(self):
        self.word2idx = {}
        self.idx2word = []
        self.counter = {}
        self.total = 0

    def add_word(self, word):
        if word not in self.word2idx:
            self.idx2word.append(word)
            self.word2idx[word] = len(self.idx2word) - 1
            self.counter.setdefault(word, 0)
        self.counter[word] += 1
        self.total += 1
        return self.word2idx[word]

    def __len__(self):
        return len(self.idx2word)

In [81]:
with open('./train.txt', 'r') as f:
    print(f.readline())
    print(f.readline())
    print(f.readline())
    print(f.readline())

 

 = Valkyria Chronicles III = 

 

 Senjō no Valkyria 3 : <unk> Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . <unk> the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " <unk> Raven " . 



In [82]:
# Let's take the four first lines of our training data:
corpus = ''
with open('./train.txt', 'r') as f:
    for i in range(4):
        corpus += f.readline()
        
# Create an empty Dictionary, separate and add all words. 
dictio = Dictionary()
words = corpus.split()
for word in words:
    dictio.add_word(word)

# Take a look at the objects created:
pp.pprint(dictio.word2idx) # index du mot dans le dictionnaire
print()
pp.pprint(dictio.idx2word) # dico
print()
pp.pprint(dictio.counter) # nombre de fois où le mot apparait
print()
pp.pprint(dictio.total) # dictionnaire complet

{'"': 60,
 '(': 9,
 ')': 18,
 ',': 12,
 '.': 14,
 '2011': 44,
 '3': 6,
 ':': 7,
 '<unk>': 8,
 '=': 0,
 '@-@': 29,
 'Battlefield': 17,
 'Chronicles': 2,
 'Europan': 70,
 'Gallia': 67,
 'III': 3,
 'Imperial': 80,
 'January': 43,
 'Japan': 24,
 'Japanese': 10,
 'Media.Vision': 37,
 'Nameless': 61,
 'PlayStation': 39,
 'Portable': 40,
 'Raven': 81,
 'Released': 41,
 'Second': 69,
 'Sega': 35,
 'Senjō': 4,
 'Valkyria': 1,
 'War': 71,
 'a': 26,
 'against': 79,
 'and': 36,
 'are': 77,
 'as': 22,
 'black': 75,
 'by': 34,
 'commonly': 19,
 'developed': 33,
 'during': 68,
 'first': 58,
 'follows': 59,
 'for': 38,
 'fusion': 49,
 'game': 32,
 'gameplay': 52,
 'in': 42,
 'is': 25,
 'it': 45,
 'its': 53,
 'lit': 13,
 'military': 63,
 'nation': 66,
 'no': 5,
 'of': 15,
 'operations': 76,
 'outside': 23,
 'parallel': 57,
 'penal': 62,
 'perform': 73,
 'pitted': 78,
 'playing': 30,
 'predecessors': 54,
 'real': 50,
 'referred': 20,
 'role': 28,
 'runs': 56,
 'same': 48,
 'secret': 74,
 'series': 47,
 

In [0]:
import numpy as np

class Corpus(object):
    def __init__(self, path):
        # We create an object Dictionary associated to Corpus
        self.dictionary = Dictionary()
        # We go through all files, adding all words to the dictionary
        self.train = self.tokenize(os.path.join(path, 'train.txt'))
        self.valid = self.tokenize(os.path.join(path, 'valid.txt'))
        self.test = self.tokenize(os.path.join(path, 'test.txt'))
        
    def tokenize(self, path):
        """Tokenizes a text file, knowing the dictionary, in order to tranform it into a list of indexes"""
        assert os.path.exists(path)
        # Add words to the dictionary
        with open(path, 'r') as f:
            tokens = 0
            for line in f:
                words = line.split() + ['<eos>']
                for word in words:
                    self.dictionary.add_word(word)
                tokens += len(words)
        
        # Once done, go through the file a second time and fill a Torch Tensor with the associated indexes 
        """
        A compléter
        """
        #ids = torch.tensor(self.dictionary.total)
        tableau = np.zeros(self.dictionary.total, dtype=int)
        with open(path, 'r') as f:
            i = 0
            for line in f:
                words = line.split() + ['<eos>']
                for word in words:
                    idx = self.dictionary.word2idx[word] # on récupère l'index
                    tableau[i] = idx
                    i+=1
        ids = torch.tensor(tableau)

        return ids

We use the corpus (wikitext-2)[https://blog.einstein.ai/the-wikitext-long-term-dependency-language-modeling-dataset/]. While it's a small dataset, we will need to reduce it if we want to train a model on it without a gpu.

In [0]:
###############################################################################
# Load data
###############################################################################

data = './'
corpus = Corpus(data)

In [85]:
#Examples and visualization
print(corpus.dictionary.total)
print(len(corpus.dictionary.idx2word))
print(len(corpus.dictionary.word2idx))

print(corpus.train.shape)
print(corpus.train[0:7])
print([corpus.dictionary.idx2word[corpus.train[i]] for i in range(7)])

print(corpus.valid.shape)
print(corpus.valid[0:7])
print([corpus.dictionary.idx2word[corpus.valid[i]] for i in range(7)])

2551843
33278
33278
torch.Size([2088628])
tensor([0, 1, 2, 3, 4, 1, 0])
['<eos>', '=', 'Valkyria', 'Chronicles', 'III', '=', '<eos>']
torch.Size([2306274])
tensor([    0,     1, 32966, 32967,     1,     0,     0])
['<eos>', '=', 'Homarus', 'gammarus', '=', '<eos>', '<eos>']


In [0]:
# We now have data under a very long list of indexes: the text is as one sequence.
# The idea now is to create batches from this. Note that this is absolutely not the best
# way to proceed with large quantities of data (where we'll try not to store huge tensors
# in memory but read them from file as we go) !
# Here, we are looking for simplicity and efficiency with regards to computation time.
# That is why we will ignore sentence separations and treat the data as one long stream that
# we will cut arbitrarily as we need.
# With the alphabet being our data, we currently have the sequence:
# [a b c d e f g h i j k l m n o p q r s t u v w x y z]
# We want to reorganize it as independant batches that will be processed independantly by the model !
# For instance, with the alphabet as the sequence and batch size 4, we'd get the 4 following sequences:
# ┌ a g m s ┐
# │ b h n t │
# │ c i o u │
# │ d j p v │
# │ e k q w │
# └ f l r x ┘
# with the last two elements being lost.
# Again, these columns are treated as independent by the model, which means that the
# dependence of e. g. 'g' on 'f' can not be learned, but allows more efficient processing.

def batchify(data, batch_size, cuda = True):
    # Cut the elements that are unnecessary
    """
    A compléter
    """
    data = data[:len(data)-len(data)%batch_size]
    
    # Reorganize the data
    """
    A compléter
    """
    data = data.view(-1, batch_size) # le -1 permet de donner directement la bonne dimension en fonction des autres

    # If we can use a GPU, let's tranfer the tensor to it
    if cuda:
        data = data.cuda()
    return data

# get_batch subdivides the source data into chunks of the appropriate length.
# If source is equal to the example output of the batchify function, with
# a sequence length (seq_len) of 3, we'd get the following two variables:
# ┌ a g m s ┐ ┌ b h n t ┐
# | b h n t | | c i o u │
# └ c i o u ┘ └ d j p v ┘
# The first variable contains the letters input to the network, while the second
# contains the one we want the network to predict (b for a, h for g, v for u, etc..)
# Note that despite the name of the function, we are cutting the data in the
# temporal dimension, since we already divided data into batches in the previous
# function. 

def get_batch(source, i, seq_len, evaluation=False):
    # Deal with the possibility that there's not enough data left for a full sequence
    # Take the input data - shift by one for the target data

    """
    A compléter
    """
    long = len(source)
    data = source[i:min(long, i+seq_len)]
    target = source[min(long,i+1):min(long,i+1+seq_len)]


    return data, target

In [87]:
#Examples and visualization
batch_size = 100
eval_batch_size = 4
train_data = batchify(corpus.train, batch_size)
val_data = batchify(corpus.valid, eval_batch_size)
test_data = batchify(corpus.test, eval_batch_size)

print(train_data.shape)
print(val_data.shape)

torch.Size([20886, 100])
torch.Size([576568, 4])


In [88]:
#Examples and visualization
input_words, target_words = get_batch(val_data, 0, 3)
pp.pprint(input_words)
pp.pprint(target_words)
input_words, target_words = get_batch(val_data, 3, 3)
pp.pprint(input_words)
pp.pprint(target_words)

tensor([[    0,     1, 32966, 32967],
        [    1,     0,     0, 32966],
        [32967,    13,   406,    23]], device='cuda:0')
tensor([[    1,     0,     0, 32966],
        [32967,    13,   406,    23],
        [   17,  6253, 19902,   310]], device='cuda:0')
tensor([[   17,  6253, 19902,   310],
        [ 1444, 19902,    13,    26],
        [   27,  2576,    16,     9]], device='cuda:0')
tensor([[ 1444, 19902,    13,    26],
        [   27,  2576,    16,     9],
        [19902,   115,    17,  4929]], device='cuda:0')


### LSTM Cells in pytorch

In [89]:
# Create a toy example of LSTM: 
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

# LSTMs expect inputs having 3 dimensions:
# - The first dimension is the temporal dimension, along which we (in our case) have the different words
# - The second dimension is the batch dimension, along which we stack the independant batches
# - The third dimension is the feature dimension, along which are the features of the vector representing the words

# In our toy case, we have inputs and outputs containing 3 features (third dimension !)
# We created a sequence of 5 different inputs (first dimension !)
# We don't use batch (the second dimension will have one lement)

# We need an initial hidden state, of the right sizes for dimension 2/3, but with only one temporal element:
# Here, it is:
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
# Why do we create a tuple of two tensors ? Because we use LSTMs: remember that they use two sets of weights,
# and two hidden states (Hidden state, and Cell state).
# If you don't remember, read: https://colah.github.io/posts/2015-08-Understanding-LSTMs/
# If we used a classic RNN, we would simply have:
# hidden = torch.randn(1, 1, 3)

# The naive way of applying a lstm to inputs is to apply it one step at a time, and loop through the sequence
for i in inputs:
    # After each step, hidden contains the hidden states (remember, it's a tuple of two states).
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    
# Alternatively, we can do the entire sequence all at once.
# The first value returned by LSTM is all of the Hidden states throughout the sequence.
# The second is just the most recent Hidden state and Cell state (you can compare the values)
# The reason for this is that:
# "out" will give you access to all hidden states in the sequence, for each temporal step
# "hidden" will allow you to continue the sequence and backpropagate later, with another sequence
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # Re-initialize
out, hidden = lstm(inputs, hidden)
pp.pprint(out)
pp.pprint(hidden)

tensor([[[-2.2452e-01,  5.4786e-02, -3.3949e-02]],

        [[-6.9429e-02, -1.9264e-02, -6.1983e-02]],

        [[ 3.2582e-01, -1.1988e-01, -1.1599e-04]],

        [[ 3.1922e-01, -1.7229e-01, -3.3374e-02]],

        [[ 3.3516e-01, -8.9476e-02,  1.0184e-02]]], grad_fn=<StackBackward>)
(tensor([[[ 0.3352, -0.0895,  0.0102]]], grad_fn=<StackBackward>),
 tensor([[[ 0.4893, -0.8318,  0.0454]]], grad_fn=<StackBackward>))


### Creating our own LSTM Model

In [0]:
# Models are usually implemented as custom nn.Module subclass
# We need to redefine the __init__ method, which creates the object
# We also need to redefine the forward method, which transform the input into outputs
# We can also add any method that we need: here, in order to initiate weights in the model
#   ntokens = size_voc
#   ninp = size_embeddings
#   nhid = size_hidden
#   nlayers = layers


class LSTMModel(nn.Module):
    def __init__(self, ntoken, ninp, nhid, nlayers, dropout=0.5):
        super(LSTMModel, self).__init__()
        # Create a dropout object to use on layers for regularization
        """
        A compléter
        """
        self.dropout = nn.Dropout(dropout) 

        # Create an encoder - which is an embedding layer
        """
        A compléter
        """
        self.encoder = nn.Embedding(ntoken, ninp) # nn.Embedding(vocab_size, embedding_dim)

        # Create the LSTM layers - find out how to stack them !
        """
        A compléter
        """
        self.lstm = nn.LSTM(ninp, nhid, nlayers, dropout=dropout) # nn.LSTM(embedding_dim, hidden_dim)

        # Create what we call the decoder: a linear transformation to map the hidden state into scores for all words in the vocabulary
        # (Note that the softmax application function will be applied out of the model)
        """
        A compléter
        """
        self.decoder =  nn.Linear(nhid, ntoken) # nn.Linear(hidden_dim, tagset_size)
        
        # Initialize non-reccurent weights 
        self.init_weights()

        self.ninp = ninp
        self.nhid = nhid
        self.nlayers = nlayers
        
    def init_weights(self):
        # Initialize the encoder and decoder weights with the uniform distribution
        initrange = 0.1
        self.encoder.weight.data.uniform_(-initrange, initrange)
        self.decoder.bias.data.fill_(0)
        self.decoder.weight.data.uniform_(-initrange, initrange)
        
    def init_hidden(self, batch_size):
        # Initialize the hidden state and cell state to zero, with the right sizes
        weight = next(self.parameters()).data
        """
        A compléter
        """
        hidden = Variable(weight.new(self.nlayers, batch_size, self.nhid).zero_())
        return (hidden, hidden)      

    def forward(self, input, hidden, return_h=False):
        # Process the input
        """
        A compléter
        """
        emb = self.drop(self.encoder(input))

        # Apply the LSTMs
        """
        A compléter
        """
        output, hidden = self.lstm(emb, hidden)
        output = self.dropt(output)
        s = output.size()

        # Decode into scores
        """
        A compléter
        """
        decoded = self.decoder(output.view(s[0]*s[1], s[2]))
        decoded = decoded.view(s[0], s[1], decoded.size(1))

        return decoded, hidden


    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores

### Building the Model

In [0]:
# Set the random seed manually for reproducibility.
torch.manual_seed(1)

# If you have Cuda installed and a GPU available
cuda = True
if torch.cuda.is_available():
    if not cuda:
        print("WARNING: You have a CUDA device, so you should probably choose cuda = True")
        
device = torch.device("cuda" if cuda else "cpu")

In [0]:
embedding_size = 200
hidden_size = 200
layers = 2
dropout = 0.5

###############################################################################
# Build the model
###############################################################################

vocab_size = len(corpus.dictionary) # A compléter
model = LSTMModel(ntoken=vocab_size, ninp=embedding_size, nhid=hidden_size, nlayers=layers, dropout=0.5)# A compléter 
model = model.to(device)
params = list(model.parameters())
criterion = nn.CrossEntropyLoss()

In [0]:
lr = 10.0
optimizer = 'sgd'
wdecay = 1.2e-6
# For gradient clipping
clip = 0.25

# Create the optimizer
optim = torch.optim.SGD(model.parameters(), lr=lr, weight_decay=wdecay, ) # A compléter

In [0]:
# Let's think about gradient propagation:
# We plan to keep the second ouput of the LSTM layer (the hidden/cell states) to initialize
# the next call to LSTM. In this way, we can back-propagate the gradient for as long as we want.
# However, this put a huge strain on the memory used by the model, since it implies retaining
# a always-growing number of tensors of gradients in the cache.
# We decide to not backpropagate through time beyond the current sequence ! 
# We use a specific function to cut the 'hidden/state cell' states from their previous dependencies
# before using them to initialize the next call to the LSTM.
# This is done with the .detach() function.

def repackage_hidden(h):
    """Wraps hidden states in new Tensors, to detach them from their history."""
    if isinstance(h, torch.Tensor):
        return # A compléter
    else:
        return tuple(repackage_hidden(v) for v in h)

In [0]:
# Other global parameters
epochs = 10
seq_len = 30
log_interval = 10
save = 'model.pt'

In [0]:
def train():
    # Turn on training mode which enables dropout.
    model.train()
    total_loss = 0.
    start_time = time.time()
    # Initialize the hidden/cell state
    """
    A compléter
    """
    for batch, i in enumerate(range(0, train_data.size(0) - 1, seq_len)):
        # Get the input/target data
        """
        A compléter
        """
        # Starting each batch, we detach the hidden state from how it was previously produced.
        # If we didn't, the model would try backpropagating all the way to start of the dataset.
        """
        A compléter
        """
        # Do the training loop: careful, look into the documentation for the criterion CrossEntropyLoss()
        """
        A compléter
        """
        # Do the gradient clipping with the function torch.nn.utils.clip_grad_norm_, then the optimization step
        """
        A compléter
        """        
        # We use .data to only accumulate the loss, and not keep track of the gradient too
        """
        A compléter
        """ 
        if batch % log_interval == 0 and batch > 0:
            cur_loss = total_loss / log_interval
            elapsed = time.time() - start_time
            print('| epoch {:3d} | {:5d}/{:5d} batches | lr {:02.2f} | ms/batch {:5.2f} | '
                    'loss {:5.2f} | ppl {:8.2f}'.format(
                epoch, batch, len(train_data) // seq_len, lr,
                elapsed * 1000 / log_interval, cur_loss, math.exp(cur_loss)))
            total_loss = 0
            start_time = time.time()

In [0]:
def evaluate(data_source):
    # Turn on evaluation mode which disables dropout.
    model.eval()
    total_loss = 0.
    # Initialize the hidden/cell state
    """
    A compléter
    """
    with torch.no_grad():
        for i in range(0, data_source.size(0) - 1, seq_len):
            """
            A compléter
            """
    return total_loss / (len(data_source) - 1)

In [0]:
# Loop over epochs.
best_val_loss = None

# At any point you can hit Ctrl + C to break out of training early.
try:
    for epoch in range(1, epochs+1):
        epoch_start_time = time.time()
        train()
        val_loss = evaluate(val_data)
        print('-' * 89)
        print('| end of epoch {:3d} | time: {:5.2f}s | valid loss {:5.2f} | '
                'valid ppl {:8.2f}'.format(epoch, (time.time() - epoch_start_time),
                                           val_loss, math.exp(val_loss)))
        print('-' * 89)
        # Save the model if the validation loss is the best we've seen so far.
        if not best_val_loss or val_loss < best_val_loss:
            with open(save, 'wb') as f:
                torch.save(model, f)
            best_val_loss = val_loss
        else:
            # Anneal the learning rate if no improvement has been seen in the validation dataset.
            lr /= 4.0
except KeyboardInterrupt:
    print('-' * 89)
    print('Exiting from training early')

# Load the best saved model.
with open(save, 'rb') as f:
    model = torch.load(f)
    # After loading, the parameters are not a continuous chunk of memory
    # This makes them a continuous chunk, and will speed up the forward pass
    model.rnn.flatten_parameters()

# Run on test data.
test_loss = evaluate(test_data)
print('=' * 89)
print('| End of training | test loss {:5.2f} | test ppl {:8.2f}'.format(
    test_loss, math.exp(test_loss)))
print('=' * 89)

In [0]:
# Implement a function to generate a fixed number of words given an input text
# You can choose the next word by doing multinomial sampling from the output distribution (which you can control using softmax temperature) 
# or simply using the argmax.